mainapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$' , views.home , name='home'),
    url(r'studygroup/(?P<selector>[\-\d\w_]+)/$', views.list_posts, name='list_posts'),
    url(r'studygroup/$', views.list_posts, name='list_posts'),
    url(r'studygroup/posts/(?P<pk>\d+)/$', views.show_post, name='show_post'),
    url(r'upload_post/',views.studygroup_postForm , name='upload_post'),
    url(r'upload_video/',views.Youtubefunction , name='upload_video'),
    url(r'upload_telegram/',views.telegramfunction , name='upload_telegram'),
    url(r'upload_fresheyes/',views.upload_fresheyes , name='upload_fresheyes'),
    url(r'telegram/',views.telegram, name='telegram'),
    url(r'youtube/',views.youtube , name='youtube'),
    url(r'fresheyes/(?P<selector>[\-\d\w_]+)/$', views.fresheyes, name='fresheyes'),
    url(r'fresheyes/$', views.fresheyes, name='fresheyes'),

    # url(r'upload_comment/',views.studygroup_commentForm , name='upload_comment'),
    #AJAX
    url(r'^ajax/delete/(?P<pk>\d+)$', views.delete_article, name='delete_article'),
    url(r'^ajax/video/delete/(?P<pk>\d+)$', views.delete_video, name='delete_video'),
    url(r'^ajax/channel/delete/(?P<pk>\d+)$', views.delete_channel, name='delete_channel'),

]

project111/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from mainapp.views import authentication
from accounts import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mainapp/', include('mainapp.urls', namespace="mainapp")),
    url(r'^$',authentication,name='home' ),
    url(r'^accounts/', include('userena.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User

from django.core.urlresolvers import reverse



Categorization_choices = (
    ('','--'),
    ('B', u'biology'),
    ('M', u'microbiology'),
    ('P', u'physiology'),
)

#youtube model

class Youtube(models.Model):
    Title=models.TextField(max_length=75)
    uploadedby=models.ForeignKey(User ,null=True)
    Description=models.TextField(max_length=150)
    Categorization=models.CharField(max_length=1, choices=Categorization_choices)
    Date= models.DateTimeField('date published',auto_now_add=True)
    is_deleted= models.BooleanField(verbose_name="هل الفديو محذوف؟",default=False)
    link=models.TextField(max_length=100)

#telegram model

class telegram_model(models.Model):
    Title=models.TextField(max_length=75)
    uploadedby=models.ForeignKey(User ,null=True)
    Description=models.TextField(max_length=150)
    Categorization=models.CharField(max_length=1, choices=Categorization_choices)
    Date= models.DateTimeField('date published',auto_now_add=True)
    is_deleted= models.BooleanField(verbose_name="هل القناة محذوف؟",default=False)
    link=models.TextField(max_length=100)

#Fresh eyes models

class fresheyes_post(models.Model):
    Title=models.TextField(max_length=75)
    uploadedby=models.ForeignKey(User ,null=True)
    help_type=models.TextField(max_length=150,default=True,verbose_name=u"نوع المساعدة؟")
    Categorization=models.CharField(max_length=1, choices=Categorization_choices)
    Date= models.DateTimeField('date published',auto_now_add=True)
    is_deleted= models.BooleanField(verbose_name="هل المستند محذوف؟",default=False)
    file= models.FileField(upload_to='Fresh_eyes/', null=True, blank=True)


    def __unicode__(self):
        return unicode(self.file) or u''


class fresheyes_comment(models.Model):
    post=models.ForeignKey(fresheyes_post)
    text=models.TextField(max_length=150)
    is_deleted= models.BooleanField(verbose_name="هل المستند محذوف؟",default=False)
    file= models.FileField(upload_to='Fresh_eyes/comment/', null=True, blank=True)


    def __unicode__(self):
        return unicode(self.file) or u''



# study group models

    # class Meta:
    #     verbose_name='مقالة'
    #     verbose_name_plural='مقالات'

class post(models.Model):
    """
    A news post.
    """
    title = models.CharField(max_length=128)
    uploadedby=models.ForeignKey(User ,null=True)
    Description=models.TextField(max_length=150)
    body = models.TextField()
    image = models.ImageField(null=True, blank=True)
    Categorization=models.CharField(max_length=1, choices=Categorization_choices)
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name="Publication Date")
    is_deleted= models.BooleanField(verbose_name="هل المقال محذوف؟",default=False)


    def has_image(self):
        return self.image != ""

    has_image.boolean = True
    has_image.short_description = "Has Image?"

    def get_summary(self):
        summary = self.body[:200]
        if len(self.body) > 200:
            summary += "..."
        return summary

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail")

class comment(models.Model):
    """
    A comment on a news post.
    """
    post = models.ForeignKey(post)
    uploadedby=models.ForeignKey(User ,null=True)
    body = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies')
    is_deleted= models.BooleanField(verbose_name="هل التعليق محذوف؟",default=False)

    def __unicode__(self):
        return "Comment by %s on post '%s'" % (self.author, self.post.title)

    def children(self): #replies
         return comment.objects.filter(parent=self)

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

#for issue selector

# class Issue(models.Model):
#     name = models.CharField(max_length=100)
#     # code_name is something more stable than 'name'
#     code_name = models.CharField(max_length=50)
#     is_blocker = models.BooleanField(default=False)
#
#     def get_selector(self):
#         return 'i-' + str(self.pk)
#
#     def __str__(self):
#         if self.is_blocker:
#             blocker_str = "blocker"
#         else:
#             blocker_str = "non-blocker"
#
#         return "{} ({})".format(self.name, blocker_str)

mainapp/forms.py
from django import forms
from mainapp.models import Youtube , telegram_model , fresheyes_post , fresheyes_comment ,post ,comment

#youtube form.
class YoutubeForm(forms.ModelForm):
    class Meta:
        model = Youtube
        fields = ['Title', 'Description','Categorization',
                 'link']


#telegram form.
class telegramForm(forms.ModelForm):
    class Meta:
        model = telegram_model
        fields= ['Title', 'Description','Categorization',
                 'link']

#fresh eyes form.
class fresheyesForm(forms.ModelForm):
    class Meta:
        model = fresheyes_post
        fields= ['Title', 'help_type','Categorization',
                 'file']


class fresheyes_commentForm(forms.ModelForm):
    class Meta:
        model = fresheyes_comment
        fields= ['text', 'file']

#study group forms

class postForm(forms.ModelForm):
     class Meta:
         model = post
         fields= ['title','Description','body','image',
                  'Categorization']


class commentForm(forms.ModelForm):
     class Meta:
         model = comment
         fields= ['body']


# class replyForm(forms.ModelForm):
#      class Meta:
#          model = comment
#          fields= ['parent']


#<<ask about the fields needed for the comment>>

mainapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.core.urlresolvers import reverse
from mainapp.forms import YoutubeForm , telegramForm , fresheyesForm , postForm, commentForm
from mainapp.models  import Youtube , telegram_model , fresheyes_post , comment , post
from django.contrib.auth.decorators import login_required
import random
import os
import posixpath
from django import template
from django.conf import settings
from django.utils import timezone
from django.views.decorators import csrf
from django.views.decorators.cache import cache_page
from django.views.decorators.http import require_POST, require_safe
from mainapp import decorators

def home(request):
     return render(request, "home.html")#response:

def authentication(request):
    # return render(request, "home.html")#response:
    if request.user.is_authenticated():
        return render(request, 'index_authenticated.html')

    else:
        return render(request, 'home.html')


#youtube functions
def youtube(request):
    biology =Youtube.objects.filter(Categorization='B' , is_deleted='False')
    microbiology =Youtube.objects.filter(Categorization='M' , is_deleted='False')
    physiology =Youtube.objects.filter(Categorization='P', is_deleted='False')

    return render(request, 'youtube.html', {'biology': biology,
                                             'microbiology':microbiology,
                                             'physiology':physiology})

def Youtubefunction(request):

    if request.method == 'POST':
        Youtube_Form = YoutubeForm(request.POST)
        if Youtube_Form.is_valid():
            Youtube_Form.save()
            return HttpResponseRedirect(reverse('mainapp:youtube'))

    elif request.method == 'GET':

        form = YoutubeForm()

    return render(request, "upload_video.html", {'form': form})


#telegram functions
def telegram(request):

    biology =telegram_model.objects.filter(Categorization='B', is_deleted='False')
    microbiology =telegram_model.objects.filter(Categorization='M',is_deleted='False')
    physiology =telegram_model.objects.filter(Categorization='P',is_deleted='False')

    return render(request, 'telegram.html', {'biology': biology,
                                             'microbiology':microbiology,
                                             'physiology':physiology})
def telegramfunction(request):

    if request.method == 'POST':
        telegram_Form = telegramForm(request.POST)
        if telegram_Form.is_valid():
            telegram_Form.save()
            return HttpResponseRedirect(reverse('mainapp:telegram'))

    elif request.method == 'GET':

        form = telegramForm()

    return render(request, "upload_telegram.html", {'form': form})


#Fresh eyes functions
def upload_fresheyes (request):
    if request.method == 'POST':
        form = fresheyesForm(request.POST, request.FILES) #the diffrence here is the type of request
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mainapp:fresheyes'))
    else:
        form = fresheyesForm()
    return render(request, "upload_fresheyes.html", {'form': form})

def upload_comment(request):
    if request.method == 'POST':
        form = commentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mainapp:fresheyes'))

    elif request.method == 'GET':

        form = commentForm()
    return {}

def fresheyes (request,selector=None):
    context = {}
    problem = fresheyes_post.objects.filter(is_deleted= False)

    if selector:
        if selector == 'biology':
            context['problem'] = problem.filter(Categorization='B')
            context['problem_type'] = "Biology"
        elif selector == 'microbiology':
            context['problem'] = problem.filter(Categorization='M')
            context['problem_type'] = "microbiology"
        elif selector == 'physiology':
            context['problem'] = problem.filter(Categorization='P')
            context['problem_type'] = "physiology"
        else:
            raise Http404
        return render(request, 'fresheyes.html', context)
    else:
        context['problem'] = problem
        context['problem_type'] = "All"
    return render(request, "fresheyes.html", context)


#study group functions
def studygroup_postForm(request):
    if request.method == 'POST':
        instance = post(uploadedby = request.user)
        Form = postForm(request.POST, request.FILES, instance=instance)
        if Form.is_valid():
            Form.save()
            return HttpResponseRedirect(reverse('mainapp:list_posts'))
    elif request.method == 'GET':
        form = postForm()
    return render(request, "upload_post.html", {'form': form})

def studygroup_commentForm(request):
    if request.method == 'POST':
        form = commentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mainapp:list_posts'))

    elif request.method == 'GET':

        form = commentForm()
    return {}
def list_posts(request,selector=None):
    context = {}
    posts = post.objects.filter(is_deleted= False)

    if selector:
        if selector == 'biology':
            context['list'] = posts.filter(Categorization='B')
            context['list_name'] = "Biology"
        elif selector == 'microbiology':
            context['list'] = posts.filter(Categorization='M')
            context['list_name'] = "microbiology"
        elif selector == 'physiology':
            context['list'] = posts.filter(Categorization='P')
            context['list_name'] = "physiology"
        else:
            raise Http404
        return render(request, 'studygroup_new.html', context)
    else:
        context['list'] = posts
        context['list_name'] = "All"
    return render(request, "studygroup_new.html", context)

def show_post(request,pk):
    article = get_object_or_404(post,pk=pk)
    comment1 = comment.objects.all()
    context= {'article':article,
              'comment1':comment1
     }
    if request.method == 'POST':
        instance = comment(post=article,uploadedby=request.user)
        form = commentForm(request.POST, instance=instance)
        if form.is_valid():
             form.save()
             return HttpResponseRedirect(
                reverse("mainapp:show_post",
                        args=(pk)))

    elif request.method == 'GET':
        form = commentForm()
    context['form']= form

    return render(request, 'studygroup_post.html',context)

# def reply_to_comment(request,pk ,commentid):
#
#     reply=replyForm.object.filter(parent='parent'
#                                   ,commentid=commentid)
#     context= {'reply':reply}
#     if request.method == 'POST':
#         reply_form = replyForm(request.POST)
#         if reply_form.is_valid():
#              reply_form.save()
#              return HttpResponseRedirect(
#                 reverse("mainapp:show_post",
#                         args=(pk,commentid)
#                         ))
#
#     elif request.method == 'GET':
#         form = replyForm()
#     context['form']= form
#
#     return render(request, 'studygroup_post.html',context)
# -
# register = template.Library()
#
# @register.simple_tag
# def random_image():
#     list_images = os.listdir(path=settings.RANDOM_IMAGES)
#     return random.choice(list_images)
# @login_required do not forget to use it @_@
#-
def reply_comment(request):
    article = get_object_or_404(post,)
    if instance.publish > timezone.now().date() or instance.draft:
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404
	#share_string = quote_plus(instance.content)
    initial_data = {
    "content_type": instance.get_content_type,
    "object_id": instance.id
    }

    form = commentForm(request.POST or None, initial=initial_data)
    if form.is_valid():
		c_type = form.cleaned_data.get("content_type")
		# content_type = ContentType.objects.get(model=c_type)
		obj_id = form.cleaned_data.get('object_id')
		content_data = form.cleaned_data.get("content")
		parent_obj = None
		try:
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None

		if parent_id:
			parent_qs = comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()


		new_comment, created = comment.objects.get_or_create(
							user = request.user,
							# content_type= content_type,
							object_id = obj_id,
							content = content_data,
							parent = parent_obj,
						)
		return HttpResponseRedirect(new_comment.content_object.get_absolute_url())


	# comments = instance.comments
    context = {
    # "title": instance.title,
    # "instance": instance,
    # "share_string": share_string,
    # "comments": comments,
    "post":post,
    "comment_form":form,
}

    return render(request, "studygroup_post.html", context)

@require_POST
@csrf.csrf_exempt
@decorators.ajax_only
def delete_article(request, pk):
    article = get_object_or_404(post, pk=pk)
        # PERMISSION CHECK
    if not request.user.is_superuser and \
       not article.uploadedby == request.user :
        raise Exception("You cannot delete that question!")


    article.is_deleted = True
    article.save()

    return  {"message": "success"}


@require_POST
@csrf.csrf_exempt
@decorators.ajax_only
def delete_video(request, pk):
    video = get_object_or_404(Youtube, pk=pk)
        # PERMISSION CHECK
    if not request.user.is_superuser and \
       not video.uploadedby == request.user :
        raise Exception("You cannot delete this video!")


    video.is_deleted = True
    video.save()

    return  {"message": "success"}

@require_POST
@csrf.csrf_exempt
@decorators.ajax_only
def delete_channel(request, pk):

mainapp/templates/fresheyes2.html
{% extends 'index.html' %} {% load static %}
{% block title%}Fresh Eyes {% endblock %}

{% block content %}

{% endblock %}

mainapp/templates/telegram.html
{% extends 'index.html' %} {% load static %}
{% block title%}telegram {% endblock %}

{% block content %}
<div class="container">
    <!-- Custom styles for this template -->
<link href="{% static 'css/telegram.css' %}" rel="stylesheet">
    <!--Custom styles for this Fonts-->
<link href="https://fonts.googleapis.com/css?family=Coda+Caption:800" rel="stylesheet">
<br>
<style>

body {
    background-color: #D3D3D3;
    background-image: url("https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX32046963.jpg");
    <!--background-repeat: no-repeat, repeat;-->
    <!--height: 100%;-->
    <!--background-position: center;-->
    <!--background-size: cover;-->
}
<!--.biology_image{-->
    <!--background-color: black ;-->
    <!--background-repeat: no-repeat, repeat;-->
    <!--height: 100%;-->
    <!--background-position: center;-->
    <!--background-size: cover;-->
<!--}-->
<!--.microbiology_image{-->
    <!--background-color: black ;-->
    <!--background-repeat: no-repeat, repeat;-->
    <!--height: 100%;-->
    <!--background-position: center;-->
    <!--background-size: cover;-->
<!--}-->
<!--.physiology_image{-->
    <!--background-color: black ;-->
    <!--background-repeat: no-repeat, repeat;-->
    <!--height: 100%;-->
    <!--background-position: center;-->
    <!--background-size: cover;-->
<!--}-->
.card{
    margin-bottom: 20px;
    background-color: white  ;
    <!--opacity: 0.9;-->

}
.card-title{
font-size: 150%;
text-align: center;
 }
.card-text{
font-size: large;
text-align: center;
}
.card-text2{
font-size: 15px;
text-align: center;
}
.btn btn-primary {
text-align: center;
}
.font{
font-family: 'Coda Caption', sans-serif;
                 color: red;
                 background-color: #B8B8BB;
                text-align: center;
                text-transform: uppercase;
                opacity: 0.9;

}

.wrap{
  float: right;
  position: relative;
  width: 40px;
  height: 40px;
  &:last-child {
    margin-bottom: 0;
  }
}

.clicker{
  background-color: white;
  outline: none;
  font-weight: 600;
	  position:absolute;
  cursor: pointer;
  padding: 0;
	  border: none;
	  height: 50px;
	  width: 50px;
  left: 4px;
  top: 4px;
	  border-radius: 100px;
	  z-index: 2;

}

.clicker:active{
	  transform: translate(0, 1px);
  height: 63px;
	  box-shadow: 0px 1px 0 0 rgb(190,190,190) inset;
}

.circle{
	  position: relative;
  border-radius:40px;
	  width: 60px;
	  height: 60px;
	  z-index: 1;
}

.circle.third{
  border-radius: 0;
}

.clicker:hover + .circle, .clicker:active + .circle {
	  animation: rotator linear .3s infinite;
}

@keyframes rotator{
	  from{ transform: rotate(0deg); }
	  to{ transform: rotate(360deg); }
}
.angled.third{
			background-image: linear-gradient(20deg,
                transparent 0%,
                transparent 30%,
                blue 30%,
								red 70%,
                transparent 70%,
                transparent 100%);
}
</style>
<section>
    <h3 class="font">Biology Section</h3>
<section class="biology_image">
    <br>
    <div class="row">
    {% for channel in biology%}
        <div class="col-xl-4 col-md-6 col-sm-12 d-flex align-items-stretch">
        <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{% static 'img/Telegram.png' %}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">{{ channel.Title }}</h5>
            <hr>
            <p class="card-text">{{ channel.Description }}</p>
            <a href="{{channel.link}}" class="btn btn-primary">Go to the channel!</a>
            {% if channel.is_deleted == False %}
                <div class="wrap">
                <button  id="delete" data-url="{% url 'mainapp:delete_channel' channel.pk %}" data-channel-pk='{{ channel.pk }}' class="clicker faster">Delete</button>
                <div class="circle angled third"></div>
                </div>
            {% endif  %}
          </div>
        </div>
        </div>
    {% endfor %}
    </div>
</section>
<br>
<section>
    <h3 class="font">microbiology Section</h3>
<section class="microbiology_image">
    <br>
    <div class="row">
    {% for channel in microbiology%}
        <div class="col-xl-4 col-md-6 col-sm-12 d-flex align-items-stretch">
        <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{% static 'img/Telegram.png' %}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">{{ channel.Title }}</h5>
            <hr>
            <p class="card-text">{{ channel.Description }}</p>
            <a href="{{channel.link}}" class="btn btn-primary">Go to the channel!</a>
            {% if channel.is_deleted == False %}
                <div class="wrap">
                <button  id="delete" data-url="{% url 'mainapp:delete_channel' channel.pk %}" data-channel-pk='{{ channel.pk }}' class="clicker faster">Delete</button>
                <div class="circle angled third"></div>
                </div>
            {% endif  %}
          </div>
        </div>
        </div>
    {% endfor %}
    </div>
</section>
<br>
<section>
    <h3 class="font">physiology Section</h3>
<section class="physiology_image">
    <br>
    <div class="row">
    {% for channel in physiology%}
        <div class="col-xl-4 col-md-6 col-sm-12 d-flex align-items-stretch">
        <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{% static 'img/Telegram.png' %}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">{{ channel.Title }}</h5>
            <hr>
            <p class="card-text">{{ channel.Description }}</p>
            <a href="{{channel.link}}" class="btn btn-primary">Go to the channel!</a>
            {% if channel.is_deleted == False %}
                <div class="wrap">
                <button  id="delete" data-url="{% url 'mainapp:delete_channel' channel.pk %}" data-channel-pk='{{ channel.pk }}' class="clicker faster">Delete</button>
                <div class="circle angled third"></div>
                </div>
            {% endif  %}
          </div>
        </div>
        </div>
    {% endfor %}
    </div>
</section>
<br>
    <a href="{% url 'mainapp:upload_telegram'%}" class="btn w3-circle btn-primary" role="button" style="float: right;">+</a>
<br>
<br>
</section>
</section>
</section>

</div>
{% endblock%}
{% block javascript %}

<script type="text/javascript">
    $(document).ready(function () {

             $('#delete,#delete1,#delete2').click(function(){
                  console.log('hi');
                  channel_pk = $(this).data('channel-pk');
                  url = $(this).data('url');

                  $.ajax({
                      url: url,
                      type: 'POST',
                      success: function(data){
                        if (data.message == 'success'){
                            window.location.href ="{% url 'mainapp:telegram' %}";
                        } else {
                        }
                      }
                  });
             });
    });
</script>
{% endblock%}

mainapp/templates/upload_fresheyes.html
{% extends 'index.html' %} {% load bootstrap4 %}

{% block title%}upload file{% endblock %}

{% block content%}
<div class="container">


<form class="form" enctype="multipart/form-data"  action="{% url 'mainapp:upload_fresheyes' %}" method="post">

    {% csrf_token %}
    {% bootstrap_form form %}
{% buttons %}
        <button type="submit" class="btn btn-primary">
             أرسل
        </button>
        {% endbuttons %}

</form>
</div>
{% endblock %}

mainapp/templates/upload_post.html
{% extends 'index.html' %} {% load bootstrap4 %}

{% block title%}post something!{% endblock %}

{% block content%}
<div class="container">
<br>
<br>
<form class="form" enctype="multipart/form-data"  action="{% url 'mainapp:upload_post' %}" method="post">

    {% csrf_token %}
    {% bootstrap_form form %}
{% buttons %}
        <button type="submit" class="btn btn-primary">
             أرسل
        </button>
        {% endbuttons %}

</form>
<br>
</div>
{% endblock %}

mainapp/templates/upload_telegram.html
 {% extends 'index.html' %} {% load bootstrap4 %}

 {% block title%}upload telegram channels{% endblock %}

{% block content%}
<div class="container">


<form class="form" enctype="multipart/form-data"  action="{% url 'mainapp:upload_telegram' %}" method="post">

    {% csrf_token %}
    {% bootstrap_form form %}
{% buttons %}
        <button type="submit" class="btn btn-primary">
             أرسل
        </button>
        {% endbuttons %}

</form>
</div>

{% endblock %}

mainapp/templates/upload_video.html
{% extends 'index.html' %} {% load bootstrap4 %}
{% block title%} upload youtube{% endblock %}
{% block content%}
<div class="container">
<form class="form" enctype="multipart/form-data"  action="{% url 'mainapp:upload_video' %}" method="post">

    {% csrf_token %}
    {% bootstrap_form form %}
{% buttons %}
        <button type="submit" class="btn btn-primary">
             أرسل
        </button>
        {% endbuttons %}

</form>
</div>
{% endblock %}